### ISSUE TITLE
Handle GitLab remotes not named 

### ISSUE THREAD

**Issue by perlun** [lighttiger2505/lab#76]
Thanks for an interesting tool!

For me, the usefulness is a bit limited since our (internal) GitLab server is not named `gitlab.foo.bar` but instead `git.foo.bar`, so the heuristics for auto-detecting the GitLab remote does not work

I did the following local tweak which works for me but is rather silly (I have an `origin` remote which is my personal fork and an `upstream` remote which is the main repository). If we could find a way to conditionalize this (perhaps with a config parameter or ENV variable), it would be great and increase the usefulness of the tool. Do you have any ideas?

```diff
diff --git a/internal/gitutil/gitutil.go b/internal/gitutil/gitutil.go
index c298b1e..c58d867 100644
--- a/internal/gitutil/gitutil.go
+++ b/internal/gitutil/gitutil.go
@@ -193,7 +193,7 @@ func (c *RemoteCollecter) collectTargetByArgs(pInfo *GitLabProjectInfo, project,
 func filterHasGitlabDomain(remoteInfos []*git.RemoteInfo) []*git.RemoteInfo {
 	var gitlabRemotes []*git.RemoteInfo
 	for _, remoteInfo := range remoteInfos {
-		if strings.HasPrefix(remoteInfo.Domain, "gitlab") {
+		if strings.HasPrefix(remoteInfo.Domain, "gitlab") || remoteInfo.Remote == "upstream" {
 			gitlabRemotes = append(gitlabRemotes, remoteInfo)
 		}
 	}
```

**Comment by lighttiger2505** [comment]
Thanks for the contribution. Your opinion is very informative.

I added the ability to virtually define gitlab domain as a solution. You can try this on the following branch.

https://github.com/lighttiger2505/lab/pull/77

The virtual gitlab domain feature adds the domain set in the lab command's configuration file to gitlab remote automatic detection.
```
profiles:
  gitlab.com:
    token: **********************
    default_group: ""
    default_project: ""
    default_assignee_id: 123
  git.foo.bar.jp: # The name is not gitlab
    token: **********************
    default_group: ""
    default_project: ""
    default_assignee_id: 345
```

For example, `git.foo.bar.jp` is not gitlab, but lab command detects it.
